version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/demos/blog"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/demos/chat"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/demos/graphql-demo"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/demos/imagetagger"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/demos/moderator"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/demos/moderator_bot"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/demos/motortwit"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/demos/polls"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/demos/shortify"
    schedule:
      interval: "daily"
